config/routes.rb
Rails.application.routes.draw do
  resources :bands
    get "like" => "bands#upvote"
    get "dislike" => "bands#downvote"

  # root 'home#index'
  root 'bands#index'

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", as: :signout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
 mount_uploader :pictureLeft, PictureUploader
 mount_uploader :pictureRight,  PictureUploader
 acts_as_votable
 serialize :photos
 # Note: serialize photos is not necessary,  this is more for displaying an album 
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.image = auth["info"]["image"]
    end
  end
  # Note:  I should have used Devise instead of omniauth gem, I only used omniauth to learn it.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy, :pictureLeft, :pictureRight]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1
  # GET /bands/1.json
  def show

  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  def upvote
     @band = Band.find(params[:id])
     @band.upvote_from current_user
      # redirect_back fallback_location: index
      # redirect_to bands_path
      band_id = (@band.id + 1).to_i
 # This line will break code if a band is ever destroyed.  Because
 #  The Show page is based off the Band ID,  will send to a page that doesn't exist
# (defined? Band.find(band_id))

      if Band.exists?(band_id)

        redirect_to band_path(band_id)
      else
        redirect_to bands_path
      end

   end

   def downvote
     @band = Band.find(params[:id])
     @band.downvote_from current_user
      # redirect_back fallback_location: index
      # redirect_to bands_url
      band_id = (@band.id + 1).to_i
    if Band.exists?(band_id)

      redirect_to band_path(band_id)
    else
      redirect_to bands_path
    end
   end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: 'Band was successfully created.' }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  # Once again the destroy method will break how the app runs because it will error out the
  # redirect_to band_path(band_id) method

  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: 'Band was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:name, :description, :pictureLeft, :pictureRight)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"])  || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed In!"
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed Out"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bands/_form.html.erb
<%= form_with(model: band, local: true) do |form| %>
  <% if band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :band_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :band_description %>
  </div>

  <div class="field">
    <%= form.label :pictureLeft, "Picture Left" %>
    <%= form.file_field :pictureLeft, id: :band_pictureLeft %>
  </div>

  <div class="field">
    <%= form.label :pictureRight, "Picture Right" %>
    <%= form.file_field :pictureRight, id: :band_pictureRight %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render 'form', band: @band %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <!-- <th>Pictureleft</th> -->
      <!-- <th>Pictureright</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.name %></td>
        <td><%= band.description %></td>
        <td><%#= band.pictureLeft %></td>
        <td><%#= band.pictureRight %></td>
        <td><%= link_to like_path(id: band.id) do %>
            Upvote
            <%= band.get_upvotes.size %>
            <% end %>
        </td>
        <td><%= link_to dislike_path(id: band.id) do %>
          Downvote
          <%= band.get_downvotes.size %>
          <% end %>
        </td>
        <td><%= link_to 'Show', band %></td>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'form', band: @band %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<style>
.center {
    margin: auto;
    width: auto;

    padding: 10px;
}
</style>
<div class= "center">
<p>
 <strong> Name: </strong>
 <%= @band.name %>
</p>

<p>
 <strong> Description: </strong>
 <%= @band.description %>
</p>

<p>
 <!-- <strong>Pictureleft:</strong> -->
 <%#= @band.pictureLeft %>
 <%#= image_tag(@band.pictureLeft_url, width: 300) if @band.pictureLeft.present? %><%#= image_tag(@band.pictureRight_url, width: 300) if @band.pictureRight.present? %>
 <!-- <strong>Pictureright:</strong> -->
 <%#= @band.pictureRight %>

 <%= link_to like_path(id: @band.id) do %><%= image_tag(@band.pictureLeft_url, width: 320) if @band.pictureLeft.present? %><% end %><%= link_to dislike_path(id: @band.id) do %><%= image_tag(@band.pictureRight_url, width: 320) if @band.pictureRight.present? %><% end %>
</p>

<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>
</div>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bands</h1>

<table>
 <thead>
   <tr>
     <th>Band Name</th>
     <th>Description</th>
     <!-- <th>Pictureleft</th>
     <th>Pictureright</th> -->
     <th colspan="3"></th>
   </tr>
 </thead>

 <tbody>
   <% @bands.each do |band| %>
     <tr>
       <td><%= band.name %></td>
       <td><%= band.description %></td>
       <td><%#= band.pictureLeft %></td>
       <td><%#= band.pictureRight %></td>
       <td><%= link_to like_path(id: band.id) do %>
           Upvote
           <%= band.get_upvotes.size %>
           <% end %>
       </td>
       <td><%= link_to dislike_path(id: band.id) do %>
         Downvote
         <%= band.get_downvotes.size %>
         <% end %>
       </td>
       <td><%= link_to 'Show', band %></td>
       <td><%= link_to 'Edit', edit_band_path(band) %></td>
       <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     </tr>
   <% end %>
 </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThisRocks_KickRocks</title>
    <%= csrf_meta_tags %>
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

  <div class="bg"></div>
  <body>
    <nav class="navbar navbar-default bg-dark navbar-fixed-top" role="navigation" >
  <!-- <nav class="navbar navbar-default navbar-fixed-top" role="navigation"> -->
  <a class="navbar-brand" href="#">
    <img src="/assets/ThisRocks.png" width="110" alt="">
  </a>
  <a class="navbar-brand" href="#">
    <img src="/assets/KickRocks.png" width="110" alt="">
  </a>
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <img src="/assets/This_rocks_banner.jpg" width="580"  alt="">
      </a>

    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/bands">Bands</a></li>
        <li class="active"><a href="/bands/9">Vote Now</a></li>
        <li class="active"><% if current_user %>
          <%#= image_tag current_user.image %> </li>
          <%= link_to "Sign Out", signout_path, id: "sign_out" %>
        <% else %>
        <li>
          <%= link_to "Sign in with GitHub", "/auth/github" %> <br>
          <%= link_to "Sign in with Instagram", "/auth/instagram" %></li>
        <% end %>

      </ul>

    </div>
  </div>

</nav>
    <div id="user-widget">
      <% if current_user %>
        Welcome <strong><%= current_user.name %></strong>!<br><br><br>
        <%#= image_tag current_user.image %>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>